FROM python:3.11-slim

WORKDIR /app

# 预装依赖，构建基础镜像
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 基础镜像标签
LABEL maintainer="trandsai"
LABEL version="1.0"
LABEL description="Trandsai Backend Base Image"